apiVersion: apps/v1
kind: Deployment
metadata:
    name: tomcat-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: tomcat
    template:
        metadata:
            labels:
                app: tomcat
        spec:
            containers:
            - name: tomcat
              image: tomcat
              ports:
              - containerPort: 8080
              resources:
                  requests:
                      cpu: 100m
                      memory: 0.1G
                  limits:
                      cpu: 500m
                      memory: 0.5G
              livenessProbe:
                  tcpSocket:
                      port: 8080
                  initialDelaySeconds: 15
                  periodSeconds: 10              
              readinessProbe:
                  tcpSocket:
                      port: 8080
                  periodSeconds: 10            