apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
spec:
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: mysql
              ports:
              - containerPort: 3306
              resources:
                  requests:
                      cpu: 100m
                      memory: 0.1G
                  limits:
                      cpu: 500m
                      memory: 0.5G
              livenessProbe:
                  tcpSocket:
                      port: 3306
                  initialDelaySeconds: 15
                  periodSeconds: 10              
              readinessProbe:
                  tcpSocket:
                      port: 3306
                  periodSeconds: 10
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: pass
              - name: MYSQL_DATABASE
                value: todo
              - name: MYSQL_USER
                value: todo
              - name: MYSQL_PASSWORD
                value: pass